CREATE TABLE `customer_payments` (
  `TDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CUSTOMER` int(11) NOT NULL,
  `INVNO` varchar(50) COLLATE latin1_general_ci DEFAULT 'NA',
  `CHQNO` varchar(50) COLLATE latin1_general_ci DEFAULT 'NA',
  `CHQDATE` date DEFAULT NULL,
  `AMT` double DEFAULT NULL COMMENT 'CHEQUE OR CASH AMOUNT COLLECTED',
  `COLLDATE` timestamp NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'WHEN THE MESSENGER COLLECTED THE CHEQUE / CASH FROM ADS IT',
  `CHEQORCASH` bit(1) NOT NULL DEFAULT b'1' COMMENT '1 CHEQUE / 0 FOR CASH /DEFAULT IS 1',
  `REFERENCENO` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`REFERENCENO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
